### ISSUE TITLE
Add test asserting that malformed TSCs do not compile

### ISSUE THREAD

**Issue by dominikmaeckel** [tudo-aqua/stars#116]
Use for example https://kotest.io/docs/assertions/compiler-matchers.html

E.g. 
```kotlin
leaf("leaf_root") {
  any("any_wrong") { }
}
```
should not compile

**Comment by tillschallau** [comment]
https://github.com/tschuchortdev/kotlin-compile-testing/issues/302

**Comment by dominikmaeckel** [comment]
Pretty much impossible since the project has to be built using Gradle to include all references.
