### ISSUE TITLE
Update `spotless` gradle plugin to fix false detekt warnings

### ISSUE THREAD

**Issue by tillschallau** [tudo-aqua/stars#184]
The `ktfmt` version that fixes the ordering of `@param` and `@property` in KDoc strings was brought to `spotless` in Version [`7.0.0.BETA2`](https://github.com/diffplug/spotless/releases/tag/maven%2F2.44.0.BETA2)

**Comment by tillschallau** [comment]
#156 has to be merged before closing this

**Comment by dominikmaeckel** [comment]
[v7.0.0.BETA4](https://github.com/diffplug/spotless/releases/tag/gradle%2F7.0.0.BETA4) out now
